// <auto-generated/>
#pragma warning disable CS0618
using JanitorHost.Sonarr.Client.Feed.V3.Calendar.SonarrIcs;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace JanitorHost.Sonarr.Client.Feed.V3.Calendar
{
    /// <summary>
    /// Builds and executes requests for operations under \feed\v3\calendar
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CalendarRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The sonarrIcs property</summary>
        public global::JanitorHost.Sonarr.Client.Feed.V3.Calendar.SonarrIcs.SonarrIcsRequestBuilder SonarrIcs
        {
            get => new global::JanitorHost.Sonarr.Client.Feed.V3.Calendar.SonarrIcs.SonarrIcsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::JanitorHost.Sonarr.Client.Feed.V3.Calendar.CalendarRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CalendarRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/feed/v3/calendar", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::JanitorHost.Sonarr.Client.Feed.V3.Calendar.CalendarRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CalendarRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/feed/v3/calendar", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
