// <auto-generated/>
#pragma warning disable CS0618
using JanitorHost.Sonarr.Client.Api.V3.Autotagging;
using JanitorHost.Sonarr.Client.Api.V3.Blocklist;
using JanitorHost.Sonarr.Client.Api.V3.Calendar;
using JanitorHost.Sonarr.Client.Api.V3.Command;
using JanitorHost.Sonarr.Client.Api.V3.Config;
using JanitorHost.Sonarr.Client.Api.V3.Customfilter;
using JanitorHost.Sonarr.Client.Api.V3.Customformat;
using JanitorHost.Sonarr.Client.Api.V3.Delayprofile;
using JanitorHost.Sonarr.Client.Api.V3.Diskspace;
using JanitorHost.Sonarr.Client.Api.V3.Downloadclient;
using JanitorHost.Sonarr.Client.Api.V3.Episode;
using JanitorHost.Sonarr.Client.Api.V3.Episodefile;
using JanitorHost.Sonarr.Client.Api.V3.Filesystem;
using JanitorHost.Sonarr.Client.Api.V3.Health;
using JanitorHost.Sonarr.Client.Api.V3.History;
using JanitorHost.Sonarr.Client.Api.V3.Importlist;
using JanitorHost.Sonarr.Client.Api.V3.Importlistexclusion;
using JanitorHost.Sonarr.Client.Api.V3.Indexer;
using JanitorHost.Sonarr.Client.Api.V3.Indexerflag;
using JanitorHost.Sonarr.Client.Api.V3.Language;
using JanitorHost.Sonarr.Client.Api.V3.Languageprofile;
using JanitorHost.Sonarr.Client.Api.V3.Localization;
using JanitorHost.Sonarr.Client.Api.V3.Log;
using JanitorHost.Sonarr.Client.Api.V3.Manualimport;
using JanitorHost.Sonarr.Client.Api.V3.Mediacover;
using JanitorHost.Sonarr.Client.Api.V3.Metadata;
using JanitorHost.Sonarr.Client.Api.V3.Notification;
using JanitorHost.Sonarr.Client.Api.V3.Parse;
using JanitorHost.Sonarr.Client.Api.V3.Qualitydefinition;
using JanitorHost.Sonarr.Client.Api.V3.Qualityprofile;
using JanitorHost.Sonarr.Client.Api.V3.Queue;
using JanitorHost.Sonarr.Client.Api.V3.Release;
using JanitorHost.Sonarr.Client.Api.V3.Releaseprofile;
using JanitorHost.Sonarr.Client.Api.V3.Remotepathmapping;
using JanitorHost.Sonarr.Client.Api.V3.Rename;
using JanitorHost.Sonarr.Client.Api.V3.Rootfolder;
using JanitorHost.Sonarr.Client.Api.V3.Seasonpass;
using JanitorHost.Sonarr.Client.Api.V3.Series;
using JanitorHost.Sonarr.Client.Api.V3.System;
using JanitorHost.Sonarr.Client.Api.V3.Tag;
using JanitorHost.Sonarr.Client.Api.V3.Update;
using JanitorHost.Sonarr.Client.Api.V3.Wanted;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace JanitorHost.Sonarr.Client.Api.V3
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v3
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class V3RequestBuilder : BaseRequestBuilder
    {
        /// <summary>The autotagging property</summary>
        public global::JanitorHost.Sonarr.Client.Api.V3.Autotagging.AutotaggingRequestBuilder Autotagging
        {
            get => new global::JanitorHost.Sonarr.Client.Api.V3.Autotagging.AutotaggingRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The blocklist property</summary>
        public global::JanitorHost.Sonarr.Client.Api.V3.Blocklist.BlocklistRequestBuilder Blocklist
        {
            get => new global::JanitorHost.Sonarr.Client.Api.V3.Blocklist.BlocklistRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The calendar property</summary>
        public global::JanitorHost.Sonarr.Client.Api.V3.Calendar.CalendarRequestBuilder Calendar
        {
            get => new global::JanitorHost.Sonarr.Client.Api.V3.Calendar.CalendarRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The command property</summary>
        public global::JanitorHost.Sonarr.Client.Api.V3.Command.CommandRequestBuilder Command
        {
            get => new global::JanitorHost.Sonarr.Client.Api.V3.Command.CommandRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The config property</summary>
        public global::JanitorHost.Sonarr.Client.Api.V3.Config.ConfigRequestBuilder Config
        {
            get => new global::JanitorHost.Sonarr.Client.Api.V3.Config.ConfigRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The customfilter property</summary>
        public global::JanitorHost.Sonarr.Client.Api.V3.Customfilter.CustomfilterRequestBuilder Customfilter
        {
            get => new global::JanitorHost.Sonarr.Client.Api.V3.Customfilter.CustomfilterRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The customformat property</summary>
        public global::JanitorHost.Sonarr.Client.Api.V3.Customformat.CustomformatRequestBuilder Customformat
        {
            get => new global::JanitorHost.Sonarr.Client.Api.V3.Customformat.CustomformatRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The delayprofile property</summary>
        public global::JanitorHost.Sonarr.Client.Api.V3.Delayprofile.DelayprofileRequestBuilder Delayprofile
        {
            get => new global::JanitorHost.Sonarr.Client.Api.V3.Delayprofile.DelayprofileRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The diskspace property</summary>
        public global::JanitorHost.Sonarr.Client.Api.V3.Diskspace.DiskspaceRequestBuilder Diskspace
        {
            get => new global::JanitorHost.Sonarr.Client.Api.V3.Diskspace.DiskspaceRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The downloadclient property</summary>
        public global::JanitorHost.Sonarr.Client.Api.V3.Downloadclient.DownloadclientRequestBuilder Downloadclient
        {
            get => new global::JanitorHost.Sonarr.Client.Api.V3.Downloadclient.DownloadclientRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The episode property</summary>
        public global::JanitorHost.Sonarr.Client.Api.V3.Episode.EpisodeRequestBuilder Episode
        {
            get => new global::JanitorHost.Sonarr.Client.Api.V3.Episode.EpisodeRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The episodefile property</summary>
        public global::JanitorHost.Sonarr.Client.Api.V3.Episodefile.EpisodefileRequestBuilder Episodefile
        {
            get => new global::JanitorHost.Sonarr.Client.Api.V3.Episodefile.EpisodefileRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The filesystem property</summary>
        public global::JanitorHost.Sonarr.Client.Api.V3.Filesystem.FilesystemRequestBuilder Filesystem
        {
            get => new global::JanitorHost.Sonarr.Client.Api.V3.Filesystem.FilesystemRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The health property</summary>
        public global::JanitorHost.Sonarr.Client.Api.V3.Health.HealthRequestBuilder Health
        {
            get => new global::JanitorHost.Sonarr.Client.Api.V3.Health.HealthRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The history property</summary>
        public global::JanitorHost.Sonarr.Client.Api.V3.History.HistoryRequestBuilder History
        {
            get => new global::JanitorHost.Sonarr.Client.Api.V3.History.HistoryRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The importlist property</summary>
        public global::JanitorHost.Sonarr.Client.Api.V3.Importlist.ImportlistRequestBuilder Importlist
        {
            get => new global::JanitorHost.Sonarr.Client.Api.V3.Importlist.ImportlistRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The importlistexclusion property</summary>
        public global::JanitorHost.Sonarr.Client.Api.V3.Importlistexclusion.ImportlistexclusionRequestBuilder Importlistexclusion
        {
            get => new global::JanitorHost.Sonarr.Client.Api.V3.Importlistexclusion.ImportlistexclusionRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The indexer property</summary>
        public global::JanitorHost.Sonarr.Client.Api.V3.Indexer.IndexerRequestBuilder Indexer
        {
            get => new global::JanitorHost.Sonarr.Client.Api.V3.Indexer.IndexerRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The indexerflag property</summary>
        public global::JanitorHost.Sonarr.Client.Api.V3.Indexerflag.IndexerflagRequestBuilder Indexerflag
        {
            get => new global::JanitorHost.Sonarr.Client.Api.V3.Indexerflag.IndexerflagRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The language property</summary>
        public global::JanitorHost.Sonarr.Client.Api.V3.Language.LanguageRequestBuilder Language
        {
            get => new global::JanitorHost.Sonarr.Client.Api.V3.Language.LanguageRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The languageprofile property</summary>
        public global::JanitorHost.Sonarr.Client.Api.V3.Languageprofile.LanguageprofileRequestBuilder Languageprofile
        {
            get => new global::JanitorHost.Sonarr.Client.Api.V3.Languageprofile.LanguageprofileRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The localization property</summary>
        public global::JanitorHost.Sonarr.Client.Api.V3.Localization.LocalizationRequestBuilder Localization
        {
            get => new global::JanitorHost.Sonarr.Client.Api.V3.Localization.LocalizationRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The log property</summary>
        public global::JanitorHost.Sonarr.Client.Api.V3.Log.LogRequestBuilder Log
        {
            get => new global::JanitorHost.Sonarr.Client.Api.V3.Log.LogRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The manualimport property</summary>
        public global::JanitorHost.Sonarr.Client.Api.V3.Manualimport.ManualimportRequestBuilder Manualimport
        {
            get => new global::JanitorHost.Sonarr.Client.Api.V3.Manualimport.ManualimportRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The mediacover property</summary>
        public global::JanitorHost.Sonarr.Client.Api.V3.Mediacover.MediacoverRequestBuilder Mediacover
        {
            get => new global::JanitorHost.Sonarr.Client.Api.V3.Mediacover.MediacoverRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The metadata property</summary>
        public global::JanitorHost.Sonarr.Client.Api.V3.Metadata.MetadataRequestBuilder Metadata
        {
            get => new global::JanitorHost.Sonarr.Client.Api.V3.Metadata.MetadataRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The notification property</summary>
        public global::JanitorHost.Sonarr.Client.Api.V3.Notification.NotificationRequestBuilder Notification
        {
            get => new global::JanitorHost.Sonarr.Client.Api.V3.Notification.NotificationRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The parse property</summary>
        public global::JanitorHost.Sonarr.Client.Api.V3.Parse.ParseRequestBuilder Parse
        {
            get => new global::JanitorHost.Sonarr.Client.Api.V3.Parse.ParseRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The qualitydefinition property</summary>
        public global::JanitorHost.Sonarr.Client.Api.V3.Qualitydefinition.QualitydefinitionRequestBuilder Qualitydefinition
        {
            get => new global::JanitorHost.Sonarr.Client.Api.V3.Qualitydefinition.QualitydefinitionRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The qualityprofile property</summary>
        public global::JanitorHost.Sonarr.Client.Api.V3.Qualityprofile.QualityprofileRequestBuilder Qualityprofile
        {
            get => new global::JanitorHost.Sonarr.Client.Api.V3.Qualityprofile.QualityprofileRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The queue property</summary>
        public global::JanitorHost.Sonarr.Client.Api.V3.Queue.QueueRequestBuilder Queue
        {
            get => new global::JanitorHost.Sonarr.Client.Api.V3.Queue.QueueRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The release property</summary>
        public global::JanitorHost.Sonarr.Client.Api.V3.Release.ReleaseRequestBuilder Release
        {
            get => new global::JanitorHost.Sonarr.Client.Api.V3.Release.ReleaseRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The releaseprofile property</summary>
        public global::JanitorHost.Sonarr.Client.Api.V3.Releaseprofile.ReleaseprofileRequestBuilder Releaseprofile
        {
            get => new global::JanitorHost.Sonarr.Client.Api.V3.Releaseprofile.ReleaseprofileRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The remotepathmapping property</summary>
        public global::JanitorHost.Sonarr.Client.Api.V3.Remotepathmapping.RemotepathmappingRequestBuilder Remotepathmapping
        {
            get => new global::JanitorHost.Sonarr.Client.Api.V3.Remotepathmapping.RemotepathmappingRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The rename property</summary>
        public global::JanitorHost.Sonarr.Client.Api.V3.Rename.RenameRequestBuilder Rename
        {
            get => new global::JanitorHost.Sonarr.Client.Api.V3.Rename.RenameRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The rootfolder property</summary>
        public global::JanitorHost.Sonarr.Client.Api.V3.Rootfolder.RootfolderRequestBuilder Rootfolder
        {
            get => new global::JanitorHost.Sonarr.Client.Api.V3.Rootfolder.RootfolderRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The seasonpass property</summary>
        public global::JanitorHost.Sonarr.Client.Api.V3.Seasonpass.SeasonpassRequestBuilder Seasonpass
        {
            get => new global::JanitorHost.Sonarr.Client.Api.V3.Seasonpass.SeasonpassRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The series property</summary>
        public global::JanitorHost.Sonarr.Client.Api.V3.Series.SeriesRequestBuilder Series
        {
            get => new global::JanitorHost.Sonarr.Client.Api.V3.Series.SeriesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The system property</summary>
        public global::JanitorHost.Sonarr.Client.Api.V3.System.SystemRequestBuilder System
        {
            get => new global::JanitorHost.Sonarr.Client.Api.V3.System.SystemRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The tag property</summary>
        public global::JanitorHost.Sonarr.Client.Api.V3.Tag.TagRequestBuilder Tag
        {
            get => new global::JanitorHost.Sonarr.Client.Api.V3.Tag.TagRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The update property</summary>
        public global::JanitorHost.Sonarr.Client.Api.V3.Update.UpdateRequestBuilder Update
        {
            get => new global::JanitorHost.Sonarr.Client.Api.V3.Update.UpdateRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The wanted property</summary>
        public global::JanitorHost.Sonarr.Client.Api.V3.Wanted.WantedRequestBuilder Wanted
        {
            get => new global::JanitorHost.Sonarr.Client.Api.V3.Wanted.WantedRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::JanitorHost.Sonarr.Client.Api.V3.V3RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public V3RequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v3", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::JanitorHost.Sonarr.Client.Api.V3.V3RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public V3RequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v3", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
