// <auto-generated/>
#pragma warning disable CS0618
using JanitorHost.Sonarr.Client.Api.V3.Mediacover.Item.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace JanitorHost.Sonarr.Client.Api.V3.Mediacover.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v3\mediacover\{seriesId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithSeriesItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the JanitorHost.Sonarr.Client.api.v3.mediacover.item.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::JanitorHost.Sonarr.Client.Api.V3.Mediacover.Item.Item.WithFilenameItemRequestBuilder"/></returns>
        public global::JanitorHost.Sonarr.Client.Api.V3.Mediacover.Item.Item.WithFilenameItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("filename", position);
                return new global::JanitorHost.Sonarr.Client.Api.V3.Mediacover.Item.Item.WithFilenameItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::JanitorHost.Sonarr.Client.Api.V3.Mediacover.Item.WithSeriesItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithSeriesItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v3/mediacover/{seriesId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::JanitorHost.Sonarr.Client.Api.V3.Mediacover.Item.WithSeriesItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithSeriesItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v3/mediacover/{seriesId}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
