// <auto-generated/>
#pragma warning disable CS0618
using JanitorHost.Sonarr.Client.Api.V3.Series.Editor;
using JanitorHost.Sonarr.Client.Api.V3.Series.Import;
using JanitorHost.Sonarr.Client.Api.V3.Series.Item;
using JanitorHost.Sonarr.Client.Api.V3.Series.Lookup;
using JanitorHost.Sonarr.Client.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace JanitorHost.Sonarr.Client.Api.V3.Series
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v3\series
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SeriesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The editor property</summary>
        public global::JanitorHost.Sonarr.Client.Api.V3.Series.Editor.EditorRequestBuilder Editor
        {
            get => new global::JanitorHost.Sonarr.Client.Api.V3.Series.Editor.EditorRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The import property</summary>
        public global::JanitorHost.Sonarr.Client.Api.V3.Series.Import.ImportRequestBuilder Import
        {
            get => new global::JanitorHost.Sonarr.Client.Api.V3.Series.Import.ImportRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The lookup property</summary>
        public global::JanitorHost.Sonarr.Client.Api.V3.Series.Lookup.LookupRequestBuilder Lookup
        {
            get => new global::JanitorHost.Sonarr.Client.Api.V3.Series.Lookup.LookupRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the JanitorHost.Sonarr.Client.api.v3.series.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::JanitorHost.Sonarr.Client.Api.V3.Series.Item.SeriesItemRequestBuilder"/></returns>
        public global::JanitorHost.Sonarr.Client.Api.V3.Series.Item.SeriesItemRequestBuilder this[int position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("id", position);
                return new global::JanitorHost.Sonarr.Client.Api.V3.Series.Item.SeriesItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the JanitorHost.Sonarr.Client.api.v3.series.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::JanitorHost.Sonarr.Client.Api.V3.Series.Item.SeriesItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::JanitorHost.Sonarr.Client.Api.V3.Series.Item.SeriesItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("id", position);
                return new global::JanitorHost.Sonarr.Client.Api.V3.Series.Item.SeriesItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::JanitorHost.Sonarr.Client.Api.V3.Series.SeriesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SeriesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v3/series{?includeSeasonImages*,tvdbId*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::JanitorHost.Sonarr.Client.Api.V3.Series.SeriesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SeriesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v3/series{?includeSeasonImages*,tvdbId*}", rawUrl)
        {
        }
        /// <returns>A List&lt;global::JanitorHost.Sonarr.Client.Models.SeriesResource&gt;</returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<List<global::JanitorHost.Sonarr.Client.Models.SeriesResource>?> GetAsync(Action<RequestConfiguration<global::JanitorHost.Sonarr.Client.Api.V3.Series.SeriesRequestBuilder.SeriesRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<List<global::JanitorHost.Sonarr.Client.Models.SeriesResource>> GetAsync(Action<RequestConfiguration<global::JanitorHost.Sonarr.Client.Api.V3.Series.SeriesRequestBuilder.SeriesRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var collectionResult = await RequestAdapter.SendCollectionAsync<global::JanitorHost.Sonarr.Client.Models.SeriesResource>(requestInfo, global::JanitorHost.Sonarr.Client.Models.SeriesResource.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
            return collectionResult?.AsList();
        }
        /// <returns>A <see cref="global::JanitorHost.Sonarr.Client.Models.SeriesResource"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::JanitorHost.Sonarr.Client.Models.SeriesResource?> PostAsync(global::JanitorHost.Sonarr.Client.Models.SeriesResource body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::JanitorHost.Sonarr.Client.Models.SeriesResource> PostAsync(global::JanitorHost.Sonarr.Client.Models.SeriesResource body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::JanitorHost.Sonarr.Client.Models.SeriesResource>(requestInfo, global::JanitorHost.Sonarr.Client.Models.SeriesResource.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::JanitorHost.Sonarr.Client.Api.V3.Series.SeriesRequestBuilder.SeriesRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::JanitorHost.Sonarr.Client.Api.V3.Series.SeriesRequestBuilder.SeriesRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::JanitorHost.Sonarr.Client.Models.SeriesResource body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::JanitorHost.Sonarr.Client.Models.SeriesResource body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::JanitorHost.Sonarr.Client.Api.V3.Series.SeriesRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::JanitorHost.Sonarr.Client.Api.V3.Series.SeriesRequestBuilder WithUrl(string rawUrl)
        {
            return new global::JanitorHost.Sonarr.Client.Api.V3.Series.SeriesRequestBuilder(rawUrl, RequestAdapter);
        }
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        #pragma warning disable CS1591
        public partial class SeriesRequestBuilderGetQueryParameters 
        #pragma warning restore CS1591
        {
            [QueryParameter("includeSeasonImages")]
            public bool? IncludeSeasonImages { get; set; }
            [QueryParameter("tvdbId")]
            public int? TvdbId { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class SeriesRequestBuilderGetRequestConfiguration : RequestConfiguration<global::JanitorHost.Sonarr.Client.Api.V3.Series.SeriesRequestBuilder.SeriesRequestBuilderGetQueryParameters>
        {
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class SeriesRequestBuilderPostRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
