// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace JanitorHost.Sonarr.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class BlocklistResource : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The customFormats property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::JanitorHost.Sonarr.Client.Models.CustomFormatResource>? CustomFormats { get; set; }
#nullable restore
#else
        public List<global::JanitorHost.Sonarr.Client.Models.CustomFormatResource> CustomFormats { get; set; }
#endif
        /// <summary>The date property</summary>
        public DateTimeOffset? Date { get; set; }
        /// <summary>The episodeIds property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<int?>? EpisodeIds { get; set; }
#nullable restore
#else
        public List<int?> EpisodeIds { get; set; }
#endif
        /// <summary>The id property</summary>
        public int? Id { get; set; }
        /// <summary>The indexer property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Indexer { get; set; }
#nullable restore
#else
        public string Indexer { get; set; }
#endif
        /// <summary>The languages property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::JanitorHost.Sonarr.Client.Models.Language>? Languages { get; set; }
#nullable restore
#else
        public List<global::JanitorHost.Sonarr.Client.Models.Language> Languages { get; set; }
#endif
        /// <summary>The message property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Message { get; set; }
#nullable restore
#else
        public string Message { get; set; }
#endif
        /// <summary>The protocol property</summary>
        public global::JanitorHost.Sonarr.Client.Models.DownloadProtocol? Protocol { get; set; }
        /// <summary>The quality property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::JanitorHost.Sonarr.Client.Models.QualityModel? Quality { get; set; }
#nullable restore
#else
        public global::JanitorHost.Sonarr.Client.Models.QualityModel Quality { get; set; }
#endif
        /// <summary>The series property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::JanitorHost.Sonarr.Client.Models.SeriesResource? Series { get; set; }
#nullable restore
#else
        public global::JanitorHost.Sonarr.Client.Models.SeriesResource Series { get; set; }
#endif
        /// <summary>The seriesId property</summary>
        public int? SeriesId { get; set; }
        /// <summary>The sourceTitle property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SourceTitle { get; set; }
#nullable restore
#else
        public string SourceTitle { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::JanitorHost.Sonarr.Client.Models.BlocklistResource"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::JanitorHost.Sonarr.Client.Models.BlocklistResource CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::JanitorHost.Sonarr.Client.Models.BlocklistResource();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "customFormats", n => { CustomFormats = n.GetCollectionOfObjectValues<global::JanitorHost.Sonarr.Client.Models.CustomFormatResource>(global::JanitorHost.Sonarr.Client.Models.CustomFormatResource.CreateFromDiscriminatorValue)?.AsList(); } },
                { "date", n => { Date = n.GetDateTimeOffsetValue(); } },
                { "episodeIds", n => { EpisodeIds = n.GetCollectionOfPrimitiveValues<int?>()?.AsList(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "indexer", n => { Indexer = n.GetStringValue(); } },
                { "languages", n => { Languages = n.GetCollectionOfObjectValues<global::JanitorHost.Sonarr.Client.Models.Language>(global::JanitorHost.Sonarr.Client.Models.Language.CreateFromDiscriminatorValue)?.AsList(); } },
                { "message", n => { Message = n.GetStringValue(); } },
                { "protocol", n => { Protocol = n.GetEnumValue<global::JanitorHost.Sonarr.Client.Models.DownloadProtocol>(); } },
                { "quality", n => { Quality = n.GetObjectValue<global::JanitorHost.Sonarr.Client.Models.QualityModel>(global::JanitorHost.Sonarr.Client.Models.QualityModel.CreateFromDiscriminatorValue); } },
                { "series", n => { Series = n.GetObjectValue<global::JanitorHost.Sonarr.Client.Models.SeriesResource>(global::JanitorHost.Sonarr.Client.Models.SeriesResource.CreateFromDiscriminatorValue); } },
                { "seriesId", n => { SeriesId = n.GetIntValue(); } },
                { "sourceTitle", n => { SourceTitle = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::JanitorHost.Sonarr.Client.Models.CustomFormatResource>("customFormats", CustomFormats);
            writer.WriteDateTimeOffsetValue("date", Date);
            writer.WriteCollectionOfPrimitiveValues<int?>("episodeIds", EpisodeIds);
            writer.WriteIntValue("id", Id);
            writer.WriteStringValue("indexer", Indexer);
            writer.WriteCollectionOfObjectValues<global::JanitorHost.Sonarr.Client.Models.Language>("languages", Languages);
            writer.WriteStringValue("message", Message);
            writer.WriteEnumValue<global::JanitorHost.Sonarr.Client.Models.DownloadProtocol>("protocol", Protocol);
            writer.WriteObjectValue<global::JanitorHost.Sonarr.Client.Models.QualityModel>("quality", Quality);
            writer.WriteObjectValue<global::JanitorHost.Sonarr.Client.Models.SeriesResource>("series", Series);
            writer.WriteIntValue("seriesId", SeriesId);
            writer.WriteStringValue("sourceTitle", SourceTitle);
        }
    }
}
#pragma warning restore CS0618
