// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace JanitorHost.Sonarr.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CustomFormatResource : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The id property</summary>
        public int? Id { get; set; }
        /// <summary>The includeCustomFormatWhenRenaming property</summary>
        public bool? IncludeCustomFormatWhenRenaming { get; set; }
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The specifications property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::JanitorHost.Sonarr.Client.Models.CustomFormatSpecificationSchema>? Specifications { get; set; }
#nullable restore
#else
        public List<global::JanitorHost.Sonarr.Client.Models.CustomFormatSpecificationSchema> Specifications { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::JanitorHost.Sonarr.Client.Models.CustomFormatResource"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::JanitorHost.Sonarr.Client.Models.CustomFormatResource CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::JanitorHost.Sonarr.Client.Models.CustomFormatResource();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "id", n => { Id = n.GetIntValue(); } },
                { "includeCustomFormatWhenRenaming", n => { IncludeCustomFormatWhenRenaming = n.GetBoolValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "specifications", n => { Specifications = n.GetCollectionOfObjectValues<global::JanitorHost.Sonarr.Client.Models.CustomFormatSpecificationSchema>(global::JanitorHost.Sonarr.Client.Models.CustomFormatSpecificationSchema.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("id", Id);
            writer.WriteBoolValue("includeCustomFormatWhenRenaming", IncludeCustomFormatWhenRenaming);
            writer.WriteStringValue("name", Name);
            writer.WriteCollectionOfObjectValues<global::JanitorHost.Sonarr.Client.Models.CustomFormatSpecificationSchema>("specifications", Specifications);
        }
    }
}
#pragma warning restore CS0618
