// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace JanitorHost.Sonarr.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class HistoryResource : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The customFormats property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::JanitorHost.Sonarr.Client.Models.CustomFormatResource>? CustomFormats { get; set; }
#nullable restore
#else
        public List<global::JanitorHost.Sonarr.Client.Models.CustomFormatResource> CustomFormats { get; set; }
#endif
        /// <summary>The customFormatScore property</summary>
        public int? CustomFormatScore { get; set; }
        /// <summary>The data property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::JanitorHost.Sonarr.Client.Models.HistoryResource_data? Data { get; set; }
#nullable restore
#else
        public global::JanitorHost.Sonarr.Client.Models.HistoryResource_data Data { get; set; }
#endif
        /// <summary>The date property</summary>
        public DateTimeOffset? Date { get; set; }
        /// <summary>The downloadId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DownloadId { get; set; }
#nullable restore
#else
        public string DownloadId { get; set; }
#endif
        /// <summary>The episode property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::JanitorHost.Sonarr.Client.Models.EpisodeResource? Episode { get; set; }
#nullable restore
#else
        public global::JanitorHost.Sonarr.Client.Models.EpisodeResource Episode { get; set; }
#endif
        /// <summary>The episodeId property</summary>
        public int? EpisodeId { get; set; }
        /// <summary>The eventType property</summary>
        public global::JanitorHost.Sonarr.Client.Models.EpisodeHistoryEventType? EventType { get; set; }
        /// <summary>The id property</summary>
        public int? Id { get; set; }
        /// <summary>The languages property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::JanitorHost.Sonarr.Client.Models.Language>? Languages { get; set; }
#nullable restore
#else
        public List<global::JanitorHost.Sonarr.Client.Models.Language> Languages { get; set; }
#endif
        /// <summary>The quality property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::JanitorHost.Sonarr.Client.Models.QualityModel? Quality { get; set; }
#nullable restore
#else
        public global::JanitorHost.Sonarr.Client.Models.QualityModel Quality { get; set; }
#endif
        /// <summary>The qualityCutoffNotMet property</summary>
        public bool? QualityCutoffNotMet { get; set; }
        /// <summary>The series property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::JanitorHost.Sonarr.Client.Models.SeriesResource? Series { get; set; }
#nullable restore
#else
        public global::JanitorHost.Sonarr.Client.Models.SeriesResource Series { get; set; }
#endif
        /// <summary>The seriesId property</summary>
        public int? SeriesId { get; set; }
        /// <summary>The sourceTitle property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SourceTitle { get; set; }
#nullable restore
#else
        public string SourceTitle { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::JanitorHost.Sonarr.Client.Models.HistoryResource"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::JanitorHost.Sonarr.Client.Models.HistoryResource CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::JanitorHost.Sonarr.Client.Models.HistoryResource();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "customFormatScore", n => { CustomFormatScore = n.GetIntValue(); } },
                { "customFormats", n => { CustomFormats = n.GetCollectionOfObjectValues<global::JanitorHost.Sonarr.Client.Models.CustomFormatResource>(global::JanitorHost.Sonarr.Client.Models.CustomFormatResource.CreateFromDiscriminatorValue)?.AsList(); } },
                { "data", n => { Data = n.GetObjectValue<global::JanitorHost.Sonarr.Client.Models.HistoryResource_data>(global::JanitorHost.Sonarr.Client.Models.HistoryResource_data.CreateFromDiscriminatorValue); } },
                { "date", n => { Date = n.GetDateTimeOffsetValue(); } },
                { "downloadId", n => { DownloadId = n.GetStringValue(); } },
                { "episode", n => { Episode = n.GetObjectValue<global::JanitorHost.Sonarr.Client.Models.EpisodeResource>(global::JanitorHost.Sonarr.Client.Models.EpisodeResource.CreateFromDiscriminatorValue); } },
                { "episodeId", n => { EpisodeId = n.GetIntValue(); } },
                { "eventType", n => { EventType = n.GetEnumValue<global::JanitorHost.Sonarr.Client.Models.EpisodeHistoryEventType>(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "languages", n => { Languages = n.GetCollectionOfObjectValues<global::JanitorHost.Sonarr.Client.Models.Language>(global::JanitorHost.Sonarr.Client.Models.Language.CreateFromDiscriminatorValue)?.AsList(); } },
                { "quality", n => { Quality = n.GetObjectValue<global::JanitorHost.Sonarr.Client.Models.QualityModel>(global::JanitorHost.Sonarr.Client.Models.QualityModel.CreateFromDiscriminatorValue); } },
                { "qualityCutoffNotMet", n => { QualityCutoffNotMet = n.GetBoolValue(); } },
                { "series", n => { Series = n.GetObjectValue<global::JanitorHost.Sonarr.Client.Models.SeriesResource>(global::JanitorHost.Sonarr.Client.Models.SeriesResource.CreateFromDiscriminatorValue); } },
                { "seriesId", n => { SeriesId = n.GetIntValue(); } },
                { "sourceTitle", n => { SourceTitle = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::JanitorHost.Sonarr.Client.Models.CustomFormatResource>("customFormats", CustomFormats);
            writer.WriteIntValue("customFormatScore", CustomFormatScore);
            writer.WriteObjectValue<global::JanitorHost.Sonarr.Client.Models.HistoryResource_data>("data", Data);
            writer.WriteDateTimeOffsetValue("date", Date);
            writer.WriteStringValue("downloadId", DownloadId);
            writer.WriteObjectValue<global::JanitorHost.Sonarr.Client.Models.EpisodeResource>("episode", Episode);
            writer.WriteIntValue("episodeId", EpisodeId);
            writer.WriteEnumValue<global::JanitorHost.Sonarr.Client.Models.EpisodeHistoryEventType>("eventType", EventType);
            writer.WriteIntValue("id", Id);
            writer.WriteCollectionOfObjectValues<global::JanitorHost.Sonarr.Client.Models.Language>("languages", Languages);
            writer.WriteObjectValue<global::JanitorHost.Sonarr.Client.Models.QualityModel>("quality", Quality);
            writer.WriteBoolValue("qualityCutoffNotMet", QualityCutoffNotMet);
            writer.WriteObjectValue<global::JanitorHost.Sonarr.Client.Models.SeriesResource>("series", Series);
            writer.WriteIntValue("seriesId", SeriesId);
            writer.WriteStringValue("sourceTitle", SourceTitle);
        }
    }
}
#pragma warning restore CS0618
