// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace JanitorHost.Sonarr.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ManualImportResource : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The customFormats property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::JanitorHost.Sonarr.Client.Models.CustomFormatResource>? CustomFormats { get; set; }
#nullable restore
#else
        public List<global::JanitorHost.Sonarr.Client.Models.CustomFormatResource> CustomFormats { get; set; }
#endif
        /// <summary>The customFormatScore property</summary>
        public int? CustomFormatScore { get; set; }
        /// <summary>The downloadId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DownloadId { get; set; }
#nullable restore
#else
        public string DownloadId { get; set; }
#endif
        /// <summary>The episodeFileId property</summary>
        public int? EpisodeFileId { get; set; }
        /// <summary>The episodes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::JanitorHost.Sonarr.Client.Models.EpisodeResource>? Episodes { get; set; }
#nullable restore
#else
        public List<global::JanitorHost.Sonarr.Client.Models.EpisodeResource> Episodes { get; set; }
#endif
        /// <summary>The folderName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FolderName { get; set; }
#nullable restore
#else
        public string FolderName { get; set; }
#endif
        /// <summary>The id property</summary>
        public int? Id { get; set; }
        /// <summary>The indexerFlags property</summary>
        public int? IndexerFlags { get; set; }
        /// <summary>The languages property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::JanitorHost.Sonarr.Client.Models.Language>? Languages { get; set; }
#nullable restore
#else
        public List<global::JanitorHost.Sonarr.Client.Models.Language> Languages { get; set; }
#endif
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The path property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Path { get; set; }
#nullable restore
#else
        public string Path { get; set; }
#endif
        /// <summary>The quality property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::JanitorHost.Sonarr.Client.Models.QualityModel? Quality { get; set; }
#nullable restore
#else
        public global::JanitorHost.Sonarr.Client.Models.QualityModel Quality { get; set; }
#endif
        /// <summary>The qualityWeight property</summary>
        public int? QualityWeight { get; set; }
        /// <summary>The rejections property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::JanitorHost.Sonarr.Client.Models.ImportRejectionResource>? Rejections { get; set; }
#nullable restore
#else
        public List<global::JanitorHost.Sonarr.Client.Models.ImportRejectionResource> Rejections { get; set; }
#endif
        /// <summary>The relativePath property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RelativePath { get; set; }
#nullable restore
#else
        public string RelativePath { get; set; }
#endif
        /// <summary>The releaseGroup property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ReleaseGroup { get; set; }
#nullable restore
#else
        public string ReleaseGroup { get; set; }
#endif
        /// <summary>The releaseType property</summary>
        public global::JanitorHost.Sonarr.Client.Models.ReleaseType? ReleaseType { get; set; }
        /// <summary>The seasonNumber property</summary>
        public int? SeasonNumber { get; set; }
        /// <summary>The series property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::JanitorHost.Sonarr.Client.Models.SeriesResource? Series { get; set; }
#nullable restore
#else
        public global::JanitorHost.Sonarr.Client.Models.SeriesResource Series { get; set; }
#endif
        /// <summary>The size property</summary>
        public long? Size { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::JanitorHost.Sonarr.Client.Models.ManualImportResource"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::JanitorHost.Sonarr.Client.Models.ManualImportResource CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::JanitorHost.Sonarr.Client.Models.ManualImportResource();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "customFormatScore", n => { CustomFormatScore = n.GetIntValue(); } },
                { "customFormats", n => { CustomFormats = n.GetCollectionOfObjectValues<global::JanitorHost.Sonarr.Client.Models.CustomFormatResource>(global::JanitorHost.Sonarr.Client.Models.CustomFormatResource.CreateFromDiscriminatorValue)?.AsList(); } },
                { "downloadId", n => { DownloadId = n.GetStringValue(); } },
                { "episodeFileId", n => { EpisodeFileId = n.GetIntValue(); } },
                { "episodes", n => { Episodes = n.GetCollectionOfObjectValues<global::JanitorHost.Sonarr.Client.Models.EpisodeResource>(global::JanitorHost.Sonarr.Client.Models.EpisodeResource.CreateFromDiscriminatorValue)?.AsList(); } },
                { "folderName", n => { FolderName = n.GetStringValue(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "indexerFlags", n => { IndexerFlags = n.GetIntValue(); } },
                { "languages", n => { Languages = n.GetCollectionOfObjectValues<global::JanitorHost.Sonarr.Client.Models.Language>(global::JanitorHost.Sonarr.Client.Models.Language.CreateFromDiscriminatorValue)?.AsList(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "path", n => { Path = n.GetStringValue(); } },
                { "quality", n => { Quality = n.GetObjectValue<global::JanitorHost.Sonarr.Client.Models.QualityModel>(global::JanitorHost.Sonarr.Client.Models.QualityModel.CreateFromDiscriminatorValue); } },
                { "qualityWeight", n => { QualityWeight = n.GetIntValue(); } },
                { "rejections", n => { Rejections = n.GetCollectionOfObjectValues<global::JanitorHost.Sonarr.Client.Models.ImportRejectionResource>(global::JanitorHost.Sonarr.Client.Models.ImportRejectionResource.CreateFromDiscriminatorValue)?.AsList(); } },
                { "relativePath", n => { RelativePath = n.GetStringValue(); } },
                { "releaseGroup", n => { ReleaseGroup = n.GetStringValue(); } },
                { "releaseType", n => { ReleaseType = n.GetEnumValue<global::JanitorHost.Sonarr.Client.Models.ReleaseType>(); } },
                { "seasonNumber", n => { SeasonNumber = n.GetIntValue(); } },
                { "series", n => { Series = n.GetObjectValue<global::JanitorHost.Sonarr.Client.Models.SeriesResource>(global::JanitorHost.Sonarr.Client.Models.SeriesResource.CreateFromDiscriminatorValue); } },
                { "size", n => { Size = n.GetLongValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::JanitorHost.Sonarr.Client.Models.CustomFormatResource>("customFormats", CustomFormats);
            writer.WriteIntValue("customFormatScore", CustomFormatScore);
            writer.WriteStringValue("downloadId", DownloadId);
            writer.WriteIntValue("episodeFileId", EpisodeFileId);
            writer.WriteCollectionOfObjectValues<global::JanitorHost.Sonarr.Client.Models.EpisodeResource>("episodes", Episodes);
            writer.WriteStringValue("folderName", FolderName);
            writer.WriteIntValue("id", Id);
            writer.WriteIntValue("indexerFlags", IndexerFlags);
            writer.WriteCollectionOfObjectValues<global::JanitorHost.Sonarr.Client.Models.Language>("languages", Languages);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("path", Path);
            writer.WriteObjectValue<global::JanitorHost.Sonarr.Client.Models.QualityModel>("quality", Quality);
            writer.WriteIntValue("qualityWeight", QualityWeight);
            writer.WriteCollectionOfObjectValues<global::JanitorHost.Sonarr.Client.Models.ImportRejectionResource>("rejections", Rejections);
            writer.WriteStringValue("relativePath", RelativePath);
            writer.WriteStringValue("releaseGroup", ReleaseGroup);
            writer.WriteEnumValue<global::JanitorHost.Sonarr.Client.Models.ReleaseType>("releaseType", ReleaseType);
            writer.WriteIntValue("seasonNumber", SeasonNumber);
            writer.WriteObjectValue<global::JanitorHost.Sonarr.Client.Models.SeriesResource>("series", Series);
            writer.WriteLongValue("size", Size);
        }
    }
}
#pragma warning restore CS0618
