// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace JanitorHost.Sonarr.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ParseResource : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The customFormats property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::JanitorHost.Sonarr.Client.Models.CustomFormatResource>? CustomFormats { get; set; }
#nullable restore
#else
        public List<global::JanitorHost.Sonarr.Client.Models.CustomFormatResource> CustomFormats { get; set; }
#endif
        /// <summary>The customFormatScore property</summary>
        public int? CustomFormatScore { get; set; }
        /// <summary>The episodes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::JanitorHost.Sonarr.Client.Models.EpisodeResource>? Episodes { get; set; }
#nullable restore
#else
        public List<global::JanitorHost.Sonarr.Client.Models.EpisodeResource> Episodes { get; set; }
#endif
        /// <summary>The id property</summary>
        public int? Id { get; set; }
        /// <summary>The languages property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::JanitorHost.Sonarr.Client.Models.Language>? Languages { get; set; }
#nullable restore
#else
        public List<global::JanitorHost.Sonarr.Client.Models.Language> Languages { get; set; }
#endif
        /// <summary>The parsedEpisodeInfo property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::JanitorHost.Sonarr.Client.Models.ParsedEpisodeInfo? ParsedEpisodeInfo { get; set; }
#nullable restore
#else
        public global::JanitorHost.Sonarr.Client.Models.ParsedEpisodeInfo ParsedEpisodeInfo { get; set; }
#endif
        /// <summary>The series property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::JanitorHost.Sonarr.Client.Models.SeriesResource? Series { get; set; }
#nullable restore
#else
        public global::JanitorHost.Sonarr.Client.Models.SeriesResource Series { get; set; }
#endif
        /// <summary>The title property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::JanitorHost.Sonarr.Client.Models.ParseResource"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::JanitorHost.Sonarr.Client.Models.ParseResource CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::JanitorHost.Sonarr.Client.Models.ParseResource();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "customFormatScore", n => { CustomFormatScore = n.GetIntValue(); } },
                { "customFormats", n => { CustomFormats = n.GetCollectionOfObjectValues<global::JanitorHost.Sonarr.Client.Models.CustomFormatResource>(global::JanitorHost.Sonarr.Client.Models.CustomFormatResource.CreateFromDiscriminatorValue)?.AsList(); } },
                { "episodes", n => { Episodes = n.GetCollectionOfObjectValues<global::JanitorHost.Sonarr.Client.Models.EpisodeResource>(global::JanitorHost.Sonarr.Client.Models.EpisodeResource.CreateFromDiscriminatorValue)?.AsList(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "languages", n => { Languages = n.GetCollectionOfObjectValues<global::JanitorHost.Sonarr.Client.Models.Language>(global::JanitorHost.Sonarr.Client.Models.Language.CreateFromDiscriminatorValue)?.AsList(); } },
                { "parsedEpisodeInfo", n => { ParsedEpisodeInfo = n.GetObjectValue<global::JanitorHost.Sonarr.Client.Models.ParsedEpisodeInfo>(global::JanitorHost.Sonarr.Client.Models.ParsedEpisodeInfo.CreateFromDiscriminatorValue); } },
                { "series", n => { Series = n.GetObjectValue<global::JanitorHost.Sonarr.Client.Models.SeriesResource>(global::JanitorHost.Sonarr.Client.Models.SeriesResource.CreateFromDiscriminatorValue); } },
                { "title", n => { Title = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::JanitorHost.Sonarr.Client.Models.CustomFormatResource>("customFormats", CustomFormats);
            writer.WriteIntValue("customFormatScore", CustomFormatScore);
            writer.WriteCollectionOfObjectValues<global::JanitorHost.Sonarr.Client.Models.EpisodeResource>("episodes", Episodes);
            writer.WriteIntValue("id", Id);
            writer.WriteCollectionOfObjectValues<global::JanitorHost.Sonarr.Client.Models.Language>("languages", Languages);
            writer.WriteObjectValue<global::JanitorHost.Sonarr.Client.Models.ParsedEpisodeInfo>("parsedEpisodeInfo", ParsedEpisodeInfo);
            writer.WriteObjectValue<global::JanitorHost.Sonarr.Client.Models.SeriesResource>("series", Series);
            writer.WriteStringValue("title", Title);
        }
    }
}
#pragma warning restore CS0618
