// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace JanitorHost.Sonarr.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class QualityModel : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The quality property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::JanitorHost.Sonarr.Client.Models.Quality? Quality { get; set; }
#nullable restore
#else
        public global::JanitorHost.Sonarr.Client.Models.Quality Quality { get; set; }
#endif
        /// <summary>The revision property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::JanitorHost.Sonarr.Client.Models.Revision? Revision { get; set; }
#nullable restore
#else
        public global::JanitorHost.Sonarr.Client.Models.Revision Revision { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::JanitorHost.Sonarr.Client.Models.QualityModel"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::JanitorHost.Sonarr.Client.Models.QualityModel CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::JanitorHost.Sonarr.Client.Models.QualityModel();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "quality", n => { Quality = n.GetObjectValue<global::JanitorHost.Sonarr.Client.Models.Quality>(global::JanitorHost.Sonarr.Client.Models.Quality.CreateFromDiscriminatorValue); } },
                { "revision", n => { Revision = n.GetObjectValue<global::JanitorHost.Sonarr.Client.Models.Revision>(global::JanitorHost.Sonarr.Client.Models.Revision.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::JanitorHost.Sonarr.Client.Models.Quality>("quality", Quality);
            writer.WriteObjectValue<global::JanitorHost.Sonarr.Client.Models.Revision>("revision", Revision);
        }
    }
}
#pragma warning restore CS0618
