// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace JanitorHost.Sonarr.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class SeasonResource : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The images property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::JanitorHost.Sonarr.Client.Models.MediaCover>? Images { get; set; }
#nullable restore
#else
        public List<global::JanitorHost.Sonarr.Client.Models.MediaCover> Images { get; set; }
#endif
        /// <summary>The monitored property</summary>
        public bool? Monitored { get; set; }
        /// <summary>The seasonNumber property</summary>
        public int? SeasonNumber { get; set; }
        /// <summary>The statistics property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::JanitorHost.Sonarr.Client.Models.SeasonStatisticsResource? Statistics { get; set; }
#nullable restore
#else
        public global::JanitorHost.Sonarr.Client.Models.SeasonStatisticsResource Statistics { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::JanitorHost.Sonarr.Client.Models.SeasonResource"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::JanitorHost.Sonarr.Client.Models.SeasonResource CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::JanitorHost.Sonarr.Client.Models.SeasonResource();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "images", n => { Images = n.GetCollectionOfObjectValues<global::JanitorHost.Sonarr.Client.Models.MediaCover>(global::JanitorHost.Sonarr.Client.Models.MediaCover.CreateFromDiscriminatorValue)?.AsList(); } },
                { "monitored", n => { Monitored = n.GetBoolValue(); } },
                { "seasonNumber", n => { SeasonNumber = n.GetIntValue(); } },
                { "statistics", n => { Statistics = n.GetObjectValue<global::JanitorHost.Sonarr.Client.Models.SeasonStatisticsResource>(global::JanitorHost.Sonarr.Client.Models.SeasonStatisticsResource.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::JanitorHost.Sonarr.Client.Models.MediaCover>("images", Images);
            writer.WriteBoolValue("monitored", Monitored);
            writer.WriteIntValue("seasonNumber", SeasonNumber);
            writer.WriteObjectValue<global::JanitorHost.Sonarr.Client.Models.SeasonStatisticsResource>("statistics", Statistics);
        }
    }
}
#pragma warning restore CS0618
