// <auto-generated/>
#pragma warning disable CS0618
using JanitorHost.Sonarr.Client.Api.V3.Config.Indexer.Item;
using JanitorHost.Sonarr.Client.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace JanitorHost.Sonarr.Client.Api.V3.Config.Indexer
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v3\config\indexer
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class IndexerRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the JanitorHost.Sonarr.Client.api.v3.config.indexer.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::JanitorHost.Sonarr.Client.Api.V3.Config.Indexer.Item.IndexerItemRequestBuilder"/></returns>
        public global::JanitorHost.Sonarr.Client.Api.V3.Config.Indexer.Item.IndexerItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("id", position);
                return new global::JanitorHost.Sonarr.Client.Api.V3.Config.Indexer.Item.IndexerItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::JanitorHost.Sonarr.Client.Api.V3.Config.Indexer.IndexerRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public IndexerRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v3/config/indexer", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::JanitorHost.Sonarr.Client.Api.V3.Config.Indexer.IndexerRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public IndexerRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v3/config/indexer", rawUrl)
        {
        }
        /// <returns>A <see cref="global::JanitorHost.Sonarr.Client.Models.IndexerConfigResource"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::JanitorHost.Sonarr.Client.Models.IndexerConfigResource?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::JanitorHost.Sonarr.Client.Models.IndexerConfigResource> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::JanitorHost.Sonarr.Client.Models.IndexerConfigResource>(requestInfo, global::JanitorHost.Sonarr.Client.Models.IndexerConfigResource.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::JanitorHost.Sonarr.Client.Api.V3.Config.Indexer.IndexerRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::JanitorHost.Sonarr.Client.Api.V3.Config.Indexer.IndexerRequestBuilder WithUrl(string rawUrl)
        {
            return new global::JanitorHost.Sonarr.Client.Api.V3.Config.Indexer.IndexerRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class IndexerRequestBuilderGetRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
