// <auto-generated/>
#pragma warning disable CS0618
using JanitorHost.Sonarr.Client.Api.V3.Wanted.Cutoff;
using JanitorHost.Sonarr.Client.Api.V3.Wanted.Missing;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace JanitorHost.Sonarr.Client.Api.V3.Wanted
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v3\wanted
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WantedRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The cutoff property</summary>
        public global::JanitorHost.Sonarr.Client.Api.V3.Wanted.Cutoff.CutoffRequestBuilder Cutoff
        {
            get => new global::JanitorHost.Sonarr.Client.Api.V3.Wanted.Cutoff.CutoffRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The missing property</summary>
        public global::JanitorHost.Sonarr.Client.Api.V3.Wanted.Missing.MissingRequestBuilder Missing
        {
            get => new global::JanitorHost.Sonarr.Client.Api.V3.Wanted.Missing.MissingRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::JanitorHost.Sonarr.Client.Api.V3.Wanted.WantedRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WantedRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v3/wanted", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::JanitorHost.Sonarr.Client.Api.V3.Wanted.WantedRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WantedRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v3/wanted", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
